DROP FUNCTION AUTOGEN_ID_TRANS;

CREATE OR REPLACE FUNCTION AUTOGEN_ID_TRANS(ID_CABANG VARCHAR2) RETURN VARCHAR2
IS
IDX NUMBER;
IDT VARCHAR2(20);
BEGIN
IDT:= TO_CHAR(SYSDATE,'DDMMYYYY') || UPPER(ID_CABANG);
SELECT COUNT(*) INTO IDX FROM HTRANS WHERE ID_TRANS LIKE '%'||IDT||'%';
IDT:= IDT||LPAD(IDX+1,4,'0');
RETURN IDT;
END;
/
SHOW ERR;

--tester
SELECT AUTOGEN_ID_TRANS('N01') FROM DUAL;